// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0MiVLKx_fNfBBtNUTJCxLjNlGh1nbR8',
    appId: '1:1070175546767:web:c031e51ac0a753c1b2affa',
    messagingSenderId: '1070175546767',
    projectId: 'mcs-mobdev-flutter',
    authDomain: 'mcs-mobdev-flutter.firebaseapp.com',
    storageBucket: 'mcs-mobdev-flutter.appspot.com',
    measurementId: 'G-EJWBT72DM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_et57oNcp7KDHUtr28jBYJel6f--uPhA',
    appId: '1:1070175546767:android:edc275f14259825cb2affa',
    messagingSenderId: '1070175546767',
    projectId: 'mcs-mobdev-flutter',
    storageBucket: 'mcs-mobdev-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsWipuJ_8Vte4J7Vp0EYFGCZ9ttTIjWok',
    appId: '1:1070175546767:ios:5ace089cfab0a26eb2affa',
    messagingSenderId: '1070175546767',
    projectId: 'mcs-mobdev-flutter',
    storageBucket: 'mcs-mobdev-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsWipuJ_8Vte4J7Vp0EYFGCZ9ttTIjWok',
    appId: '1:1070175546767:ios:762ef390a0476431b2affa',
    messagingSenderId: '1070175546767',
    projectId: 'mcs-mobdev-flutter',
    storageBucket: 'mcs-mobdev-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseAuthProject.RunnerTests',
  );
}
